- name: Build database instance image
  hosts: all
  become: true
  roles:
  - db

### Previous solution
# - name: Build database instance image
#   hosts: all
#   become: true
#   tasks:
#   - name: Install MongoDB repo key
#     apt_key:
#       url: https://www.mongodb.org/static/pgp/server-4.2.asc
#       state: present
  
#   - name: Add MongoDB repository
#     apt_repository:
#       repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
#       state: present
  
#   - name: Install MongoDB
#     apt:
#       name: mongodb-org
#       update_cache: yes
#       allow_unauthenticated: yes
  
#   - name: Turining on the Mongo service
#     systemd:
#       name: mongod
#       state: started
#       enabled: yes
