---
# tasks file for app
- name: Show info about the env host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Add unit file for Puma
  copy:
    src: puma-reddit.service
    dest: /etc/systemd/system/puma-reddit.service

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/ubuntu/db_config
    owner: ubuntu
    group: ubuntu
