---
- name: Add unit file for Puma
  template:
    src: puma-reddit.service.j2
    dest: /etc/systemd/system/puma-reddit.service

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: "/home/{{ deploy_user }}/db_config"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
