- name: Configuring MongoDB
  hosts: db
  tags: db-tag
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0
  tasks:
  - name: Change mongo config file
    template:
      src: templates/mongod.conf.j2
      dest: /etc/mongod.conf
      mode: 0644
    notify: restart mongod

  handlers:
  - name: restart mongod
    service: name=mongod state=restarted

- name: Configuring application
  hosts: app
  tags: app-tag
  become: true
  vars:
    db_host: 10.128.0.28
  tasks:
  - name: Add unit file for Puma
    copy:
      src: files/puma-reddit.service
      dest: /etc/systemd/system/puma-reddit.service
    notify: reload puma
  
  - name: Add config for DB connection
    template:
      src: templates/db_config.j2
      dest: /home/ubuntu/db_config
      owner: ubuntu
      group: ubuntu

  - name: enable puma
    systemd: name=puma-reddit enabled=yes

  handlers:
  - name: reload puma
    become: true
    systemd:
      daemon_reload: true # Выполнение перезагрузки демонов после изменения сервиса
      name: puma-reddit
      state: restarted

- name: Deploying application
  hosts: app
  tags: deploy-tag
  tasks:
  - name: Fetch the latest version of application code
    changed_when: true
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith
    tags: deploy-tag
    notify: reload puma
  
  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit
    tags: deploy-tag

  handlers:
  - name: reload puma
    become: true
    systemd:
      daemon_reload: true # Выполнение перезагрузки демонов после изменения сервиса
      name: puma-reddit
      state: restarted
